### ISSUE TITLE
TWO-WIRE ETH CLICK on esp32 & Micropython

### ISSUE THREAD

**Issue by DuaneKaufman** [MicrochipTech/oa-tc6-lib#11]
Dear Sirs,
My name is Duane Kaufman, and I am working on getting the Mikroe TWO-WIRE ETH CLICK working over SPI to an ESP32 DevkitC board running Micropython.

Has anyone done something like this before, and if so, can you share insights (and code!)?

Sincerely,
Duane

**Comment by DuaneKaufman** [comment]
Dear Thorsten, 

> unfortunately we did not port the corresponding library to ESP32 nor to Micropython. And there is also no plan to do so.. 

No problem at all, I appreciate what's been done already! 

I plan on starting out using ESP-IDF and FreeRTOS - are any of the examples already put together close to a FreeRTOS implementation? 

Again, thanks for all your effort. 

Sincerely, 
Duane

**Comment by tkummermehr** [comment]
Dear Duane,

yes, we have a project with our Harmony implementation using FreeRTOS. But there are no changes needed for TC6 library. Just make sure to protect the library from be entered from different RTOS-tasks (using Semaphores).
[tcpip_iperf_lan865x](https://github.com/Microchip-MPLAB-Harmony/net_10base_t1s/tree/master/apps/tcpip_iperf_lan865x)

If you are going to port the code to Python, it might be easier for you to start with a synchronous (blocking) approach. I made an own branch therefor:
[sync-branch](https://github.com/MicrochipTech/oa-tc6-lib/tree/no-queues-synchronous)

Sincery,
Thorsten

**Comment by DuaneKaufman** [comment]
Dear Thorsten, 

> yes, we have a project with our Harmony implementation using FreeRTOS. But there are no changes needed for TC6 library. 
> Just make sure to protect the library from be entered from different RTOS-tasks (using Semaphores). [ https://github.com/Microchip-MPLAB-Harmony/net_10base_t1s/tree/master/apps/tcpip_iperf_lan865x | tcpip_iperf_lan865x ] 

Good to know/review, thanks. 

> If you are going to port the code to Python, it might be easier for you to start with a synchronous (blocking) approach. I made an own branch therefor: [ https://github.com/MicrochipTech/oa-tc6-lib/tree/no-queues-synchronous | sync-branch ] 

Well, specifically MicroPython ( [ https://micropython.org/ | https://micropython.org/ ] ), which already has a couple SPI-based Ethernet chips incorporated. 

I may try a pure-Python version first, to get acquainted with the details, patterned after the Adafruit WizNet5k work: [ https://github.com/adafruit/Adafruit_CircuitPython_Wiznet5k | https://github.com/adafruit/Adafruit_CircuitPython_Wiznet5k ] 

Thanks again, 

Duane

**Comment by DuaneKaufman** [comment]
Dear Thorsten, 

I appreciate your help. 

I was wondering, does this library (or, more fundamentally, the LAN8651 chip) support topology discovery? 
[ https://opensig.org/download/document/OPEN_Alliance_10BASET1S_Topology_Discovery_V1.0.pdf | https://opensig.org/download/document/OPEN_Alliance_10BASET1S_Topology_Discovery_V1.0.pdf ] 

Sincerely, 
Duane

**Comment by tkummermehr** [comment]
Dear Duane,

Please contact the Microchip support for further information.

Best regards,
Thorsten
