### ISSUE TITLE
Question regarding license

### ISSUE THREAD

**Issue by lmajewski** [MicrochipTech/oa-tc6-lib#13]
Dear Microchip,

I would like to ask about the SPDX (https://spdx.org/licenses/) license which corresponds for this code.

What are the terms of using the oa-tc6-lib ?

**Comment by tkummermehr** [comment]
Dear Imajewski,

we use our own proprietary license:
https://github.com/MicrochipTech/oa-tc6-lib/blob/main/Microchip_SLA001.md

**Comment by lmajewski** [comment]
Thanks for the reply.

I've read the pointed above document. However, I couldn't find any information if this license is under the Open Source Initiative (OSI) - https://opensource.org/licenses/

Please correct me if I'm wrong, but it looks like it is NOT.

For the project on which I'm working (Zephyr) - it is required to be one of the listed ones. Do you have any future plans to release the TC6 OA library for T1S under one of OSI licenses?

**Comment by tkummermehr** [comment]
Dear Imajewski,

it is true, our license is not on that list. 

For further discussions (as GitHub is not the right place to do that), please create a support ticket. 

Creating and tracking support cases requires a myMicrochip account.  For information on how to create this account and how to create a support case, follow the link below to a short article titled "How to submit a technical support case?".  This article will guide you through the process.

      

https://microchipsupport.force.com/s/article/How-to-submit-a-case

**Comment by lmajewski** [comment]
I've filled the Case -  01333762.

Let's wait for the reply.
